const data = {
  salesChartData: {
    xLabels: [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ],
    data: [
      {
        label: "BryBelly",
        values: [
          2115, 1562, 1584, 1892, 1087, 2223, 2966, 2448, 2905, 3838, 2917,
          3327,
        ],
      },
      {
        label: "Blooming Bath",
        values: [
          958, 724, 629, 883, 915, 1214, 1476, 1212, 1554, 2128, 466, 1827,
        ],
      },
      {
        label: "NaturSutten",
        values: [
          1214, 883, 1212, 2128, 1554, 958, 724, 915, 1827, 629, 1476, 1466,
        ],
      },
    ],
  },

  brands: [
    {
      id: 1,
      brand: "BryBelly",
      revenue: 25000000,
      comparisonRevenue: 19000000,
      revenueChange: 14,
    },
    {
      id: 2,
      brand: "Blooming Bath",
      revenue: 7000000,
      comparisonRevenue: 5000000,
      revenueChange: 6,
    },
    {
      id: 3,
      brand: "NaturSutten",
      revenue: 600000,
      comparisonRevenue: 300000,
      revenueChange: 30,
    },
  ],

  products: [
    {
      id: 1,
      brand: "BryBelly",
      name: "Product 1",
      revenue: 2500,
      comparisonRevenue: 1900,
      revenueChange: 14,
    },
    {
      id: 2,
      brand: "BryBelly",
      name: "Product 2",
      revenue: 700,
      comparisonRevenue: 500,
      revenueChange: 6,
    },
    {
      id: 3,
      brand: "BryBelly",
      name: "Product 3",
      revenue: 600,
      comparisonRevenue: 300,
      revenueChange: 30,
    },
    {
      id: 4,
      brand: "Blooming Bath",
      name: "Product 1",
      revenue: 2500,
      comparisonRevenue: 1900,
      revenueChange: 14,
    },
    {
      id: 6,
      brand: "Blooming Bath",
      name: "Product 2",
      revenue: 700,
      comparisonRevenue: 500,
      revenueChange: 6,
    },
    {
      id: 6,
      brand: "Blooming Bath",
      name: "Product 3",
      revenue: 600,
      comparisonRevenue: 300,
      revenueChange: 30,
    },
    {
      id: 7,
      brand: "NaturSutten",
      name: "Product 1",
      revenue: 2500,
      comparisonRevenue: 1900,
      revenueChange: 14,
    },
    {
      id: 8,
      brand: "NaturSutten",
      name: "Product 2",
      revenue: 700,
      comparisonRevenue: 500,
      revenueChange: 6,
    },
    {
      id: 9,
      brand: "NaturSutten",
      name: "Product 3",
      revenue: 600,
      comparisonRevenue: 300,
      revenueChange: 30,
    },
  ],

  companyCategories: [
    { id: 1, name: "Baby" },
    { id: 2, name: "Novelty" },
    { id: 3, name: "Pet" },
    { id: 4, name: "Outdoor" },
  ],
  companies: [
    {
      category_name: "Baby",
      company_category_id: 1,
      id: 2,
      name: "Blooming Bath",
      nickname: "Blooming Bath",
    },
    {
      category_name: "Baby",
      company_category_id: 1,
      id: 4,
      name: "Natursutten",
      nickname: "Natursutten",
    },
    {
      category_name: "Baby",
      company_category_id: 1,
      id: 6,
      name: "Mimijumi",
      nickname: "Mimijumi",
    },
    {
      category_name: "Novelty",
      company_category_id: 2,
      id: 1,
      name: "Brybelly",
      nickname: "Brybelly",
    },
    {
      category_name: "Pet",
      company_category_id: 3,
      id: 3,
      name: "Downtown Pet Supply",
      nickname: "DTPS",
    },
    {
      category_name: "Outdoor",
      company_category_id: 4,
      id: 5,
      name: "Hyke & Byke",
      nickname: "Hyke & Byke",
    },
  ],
  marketCategories: [
    { id: 1, market: "Amazon" },
    { id: 2, market: "Shopify" },
  ],
  markets: [
    {
      category_id: 1,
      country_code: "US",
      country_id: 1,
      currency_id: 1,
      currency_symbol: "USD",
      id: 1,
      name: "Amazon US",
      native_identifier: "ATVPDKIKX0DER",
      url: "https://www.amazon.com/",
    },
    {
      category_id: 1,
      country_code: "CA",
      country_id: 2,
      currency_id: 2,
      currency_symbol: "CAD",
      id: 2,
      name: "Amazon CA",
      native_identifier: "A2EUQ1WTGCTBG2",
      url: "https://www.amazon.ca/",
    },
    {
      category_id: 1,
      country_code: "GB",
      country_id: 3,
      currency_id: 3,
      currency_symbol: "GBP",
      id: 3,
      name: "Amazon UK",
      native_identifier: "A1F83G8C2ARO7P",
      url: "https://www.amazon.co.uk/",
    },
    {
      category_id: 1,
      country_code: "FR",
      country_id: 4,
      currency_id: 4,
      currency_symbol: "EUR",
      id: 4,
      name: "Amazon FR",
      native_identifier: "A13V1IB3VIYZZH",
      url: "https://www.amazon.fr/",
    },
    {
      category_id: 1,
      country_code: "DE",
      country_id: 5,
      currency_id: 4,
      currency_symbol: "EUR",
      id: 5,
      name: "Amazon DE",
      native_identifier: "A1PA6795UKMFR9",
      url: "https://www.amazon.de/",
    },
    {
      category_id: 1,
      country_code: "IT",
      country_id: 6,
      currency_id: 4,
      currency_symbol: "EUR",
      id: 6,
      name: "Amazon IT",
      native_identifier: "APJ6JRA9NG5V4",
      url: "https://www.amazon.it/",
    },
    {
      category_id: 1,
      country_code: "ES",
      country_id: 7,
      currency_id: 4,
      currency_symbol: "EUR",
      id: 7,
      name: "Amazon ES",
      native_identifier: "A1RKKUPIHCS9HS",
      url: "https://www.amazon.es/",
    },
    {
      category_id: 1,
      country_code: "NL",
      country_id: 9,
      currency_id: 4,
      currency_symbol: "EUR",
      id: 8,
      name: "Amazon NL",
      native_identifier: "A1805IZSGTT6HS",
      url: "https://www.amazon.nl/",
    },
    {
      category_id: 1,
      country_code: "MX",
      country_id: 8,
      currency_id: 5,
      currency_symbol: "MXN",
      id: 9,
      name: "Amazon MX",
      native_identifier: "A1AM78C64UM0Y8",
      url: "https://www.amazon.mx/",
    },
    {
      category_id: 2,
      country_code: "US",
      country_id: 1,
      currency_id: 1,
      currency_symbol: "USD",
      id: 10,
      name: "Shopify",
      native_identifier: "SHOPIFY",
      url: "https://www.shopify.com/",
    },
  ],
};

export default data;
